In [3]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam
import pickle
import numpy as np
import os

In [2]:
!pip install tensorflow


  Using cached tensorflow-2.11.0-cp39-cp39-win_amd64.whl (1.9 kB)
  Using cached tensorflow_intel-2.11.0-cp39-cp39-win_amd64.whl (266.3 MB)
  Using cached keras-2.11.0-py2.py3-none-any.whl (1.7 MB)
  Using cached flatbuffers-23.1.21-py2.py3-none-any.whl (26 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached libclang-15.0.6.1-py2.py3-none-win_amd64.whl (23.2 MB)
  Using cached tensorboard-2.11.2-py3-none-any.whl (6.0 MB)
  Using cached tensorflow_io_gcs_filesystem-0.30.0-cp39-cp39-win_amd64.whl (1.5 MB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached grpcio-1.51.1-cp39-cp39-win_amd64.whl (3.7 MB)
  Using cached tensorflow_estimator-2.11.0-py2.py3-none-any.whl (439 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached Markdown-3.4.1-py3-none-any.whl (93 kB)
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)


In [24]:
file = open("‪C:\Users\rakesh\Downloads\hindi_text.txt", "r+")

# store file in list
lines = []
for i in file:
    lines.append(i)

# Convert list to string
data = ""
for i in lines:
  data = ' '. join(lines) 

#replace unnecessary stuff with space
data = data.replace('\n', '').replace('\r', '').replace('\ufeff', '').replace('“','').replace('”','')  #new line, carriage return, unicode character --> replace by space

#remove unnecessary spaces 
data = data.split()
data = ' '.join(data)
data[:500]

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 12-13: truncated \UXXXXXXXX escape (Temp/ipykernel_262780/1759599084.py, line 1)

In [26]:
with open("hindi_text.txt", "r+") as file:
    #file.write("Hello world!")
    #file.seek(0)
    data = file.read()
print(data)

"Herbert society ke sabhi log sulochana ke ghar aate aur saree taiyari Yoko dekhte ho jate kyonki navratri ka pandal sulochana ke hegre lagta tha Ek din subah subah ghar ke sabhi log Ek saath baat karna stock are hote Hain tabhi sulochana Ki saheli urmila uske ghar aati hai aur bolti hai Kal se navratri chalaye puja khesari tyari shuru kar diya tune kyon nahi Kari ha bilakul tujhe lagta hai main navratri ke pujan me koi kami rakhangi Aaj Tak koi kami rahe hai kya aaj rukku g nahin bilkul nhi Aaj Tak Teri yari me kabhi koi kami nahi aaye tab bhi to society ke sabhi log navratri poojan ko tere ghar aate hai aur waise bhi tere dono ladki shadi navratri me Hui thi tune bilkul sahee kahan AB tujhe chinta kis baat Ki AB toh Teri mother ke liye Teri doba hai tu basa ram kare Teri baat bilkul sahee hai aur main chalti Hu ghar me bahut Kam hai aur meri behna hai Teri bahon Ki tarah nahin Jana tere ghar se bhar rahe to Natalie kya hoga mera ghar ka sulochana Ki dono boman sarvagun sampanna thi l

In [27]:
#replace unnecessary stuff with space
data = data.replace('\n', '').replace('\r', '').replace('\ufeff', '').replace('“','').replace('”','')  #new line, carriage return, unicode character --> replace by space

#remove unnecessary spaces 
data = data.split()
data = ' '.join(data)
data[:500]

'"Herbert society ke sabhi log sulochana ke ghar aate aur saree taiyari Yoko dekhte ho jate kyonki navratri ka pandal sulochana ke hegre lagta tha Ek din subah subah ghar ke sabhi log Ek saath baat karna stock are hote Hain tabhi sulochana Ki saheli urmila uske ghar aati hai aur bolti hai Kal se navratri chalaye puja khesari tyari shuru kar diya tune kyon nahi Kari ha bilakul tujhe lagta hai main navratri ke pujan me koi kami rakhangi Aaj Tak koi kami rahe hai kya aaj rukku g nahin bilkul nhi Aaj'

In [28]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])

# saving the tokenizer for predict function
pickle.dump(tokenizer, open('token.pkl', 'wb'))

sequence_data = tokenizer.texts_to_sequences([data])[0]
sequence_data[:15]

[715, 270, 3, 103, 183, 108, 3, 15, 184, 4, 466, 716, 717, 185, 6]

In [48]:
sequence_data

[715,
 270,
 3,
 103,
 183,
 108,
 3,
 15,
 184,
 4,
 466,
 716,
 717,
 185,
 6,
 85,
 718,
 109,
 17,
 340,
 108,
 3,
 719,
 136,
 34,
 13,
 22,
 137,
 137,
 15,
 3,
 103,
 183,
 13,
 39,
 25,
 158,
 720,
 40,
 94,
 26,
 721,
 108,
 2,
 722,
 723,
 68,
 15,
 271,
 1,
 4,
 467,
 1,
 341,
 5,
 109,
 468,
 86,
 342,
 469,
 95,
 8,
 73,
 223,
 186,
 11,
 470,
 343,
 187,
 110,
 136,
 1,
 31,
 109,
 3,
 724,
 10,
 29,
 272,
 725,
 58,
 65,
 29,
 272,
 123,
 1,
 14,
 58,
 726,
 273,
 23,
 188,
 104,
 58,
 65,
 96,
 727,
 10,
 59,
 29,
 272,
 11,
 471,
 274,
 12,
 9,
 270,
 3,
 103,
 183,
 109,
 728,
 7,
 159,
 15,
 184,
 1,
 4,
 344,
 12,
 159,
 53,
 189,
 472,
 109,
 10,
 224,
 32,
 223,
 188,
 345,
 729,
 74,
 110,
 275,
 225,
 25,
 2,
 74,
 42,
 96,
 473,
 3,
 37,
 96,
 730,
 1,
 190,
 731,
 276,
 75,
 96,
 25,
 188,
 345,
 1,
 4,
 31,
 474,
 105,
 15,
 10,
 33,
 111,
 1,
 4,
 60,
 732,
 1,
 96,
 733,
 2,
 138,
 23,
 475,
 159,
 15,
 5,
 476,
 123,
 9,
 734,
 14,
 226,
 97,
 15,
 17,
 10

In [49]:
tokenizer.word_index

{'hai': 1,
 'ki': 2,
 'ke': 3,
 'aur': 4,
 'se': 5,
 'ho': 6,
 'ko': 7,
 'kar': 8,
 'to': 9,
 'me': 10,
 'nahi': 11,
 'bhi': 12,
 'ek': 13,
 'kya': 14,
 'ghar': 15,
 'hi': 16,
 'ka': 17,
 'mujhe': 18,
 'apni': 19,
 'jati': 20,
 'par': 21,
 'din': 22,
 'nahin': 23,
 'or': 24,
 'baat': 25,
 'hain': 26,
 'a': 27,
 'kuch': 28,
 'koi': 29,
 'na': 30,
 'main': 31,
 'thi': 32,
 'bahut': 33,
 'tha': 34,
 'tum': 35,
 'aap': 36,
 'liye': 37,
 'karte': 38,
 'saath': 39,
 'are': 40,
 'wo': 41,
 'toh': 42,
 'ye': 43,
 'is': 44,
 'mein': 45,
 'use': 46,
 'mirch': 47,
 'maa': 48,
 'hari': 49,
 'ne': 50,
 'mere': 51,
 'apne': 52,
 'dono': 53,
 'hota': 54,
 'jo': 55,
 'bana': 56,
 'baad': 57,
 'aaj': 58,
 'kabhi': 59,
 'meri': 60,
 'pyar': 61,
 'rahi': 62,
 'khane': 63,
 'alvira': 64,
 'tak': 65,
 'dekh': 66,
 'i': 67,
 'uske': 68,
 'lekin': 69,
 'aise': 70,
 'ji': 71,
 'maine': 72,
 'diya': 73,
 'ab': 74,
 'kare': 75,
 'kaise': 76,
 'jata': 77,
 'phir': 78,
 'kisi': 79,
 'sab': 80,
 'hoti': 81,
 'khan

In [29]:
vocab_size = len(tokenizer.word_index) + 1
print(vocab_size)

1924


In [30]:
sequences = []

for i in range(3, len(sequence_data)):
    words = sequence_data[i-3:i+1]
    sequences.append(words)
    
print("The Length of sequences are: ", len(sequences))
sequences = np.array(sequences)
sequences[:10]

The Length of sequences are:  6646


array([[715, 270,   3, 103],
       [270,   3, 103, 183],
       [  3, 103, 183, 108],
       [103, 183, 108,   3],
       [183, 108,   3,  15],
       [108,   3,  15, 184],
       [  3,  15, 184,   4],
       [ 15, 184,   4, 466],
       [184,   4, 466, 716],
       [  4, 466, 716, 717]])

In [33]:
X = []
y = []

for i in sequences:
    X.append(i[0:3])
    y.append(i[3])
    
X = np.array(X)
y = np.array(y)

In [34]:
print("Data: ", X[:10])
print("Response: ", y[:10])

Data:  [[715 270   3]
 [270   3 103]
 [  3 103 183]
 [103 183 108]
 [183 108   3]
 [108   3  15]
 [  3  15 184]
 [ 15 184   4]
 [184   4 466]
 [  4 466 716]]
Response:  [103 183 108   3  15 184   4 466 716 717]


In [35]:
y = to_categorical(y, num_classes=vocab_size)
y[:5]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

# LSTM

In [36]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=3))
model.add(LSTM(1000, return_sequences=True))
model.add(LSTM(1000))
model.add(Dense(1000, activation="relu"))
model.add(Dense(vocab_size, activation="softmax"))

In [37]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 10)             19240     
                                                                 
 lstm (LSTM)                 (None, 3, 1000)           4044000   
                                                                 
 lstm_1 (LSTM)               (None, 1000)              8004000   
                                                                 
 dense (Dense)               (None, 1000)              1001000   
                                                                 
 dense_1 (Dense)             (None, 1924)              1925924   
                                                                 
Total params: 14,994,164
Trainable params: 14,994,164
Non-trainable params: 0
_________________________________________________________________


In [38]:
from tensorflow.keras.callbacks import ModelCheckpoint

checkpoint = ModelCheckpoint("next_words.h5", monitor='loss', verbose=1, save_best_only=True)
model.compile(loss="categorical_crossentropy", optimizer=Adam(learning_rate=0.001), metrics=['accuracy'])
model.fit(X, y, epochs=7, batch_size=64, callbacks=[checkpoint])

Epoch 1/7
104/104 [==============================] - ETA: 0s - loss: 6.9694 - accuracy: 0.0451
Epoch 1: loss improved from inf to 6.96945, saving model to next_words.h5
104/104 [==============================] - 53s 366ms/step - loss: 6.9694 - accuracy: 0.0451
Epoch 2/7
104/104 [==============================] - ETA: 0s - loss: 6.5815 - accuracy: 0.0460
Epoch 2: loss improved from 6.96945 to 6.58152, saving model to next_words.h5
104/104 [==============================] - 36s 344ms/step - loss: 6.5815 - accuracy: 0.0460
Epoch 3/7
104/104 [==============================] - ETA: 0s - loss: 6.4844 - accuracy: 0.0460
Epoch 3: loss improved from 6.58152 to 6.48442, saving model to next_words.h5
104/104 [==============================] - 37s 354ms/step - loss: 6.4844 - accuracy: 0.0460
Epoch 4/7
104/104 [==============================] - ETA: 0s - loss: 6.3629 - accuracy: 0.0468
Epoch 4: loss improved from 6.48442 to 6.36285, saving model to next_words.h5
104/104 [===========================

# Bidirectional LSTM

In [39]:
import pandas as pd
import os
import numpy as np

import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional,RNN
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

In [40]:
model = Sequential()
model.add(Embedding(vocab_size, 100, input_length=3))
model.add(Bidirectional(LSTM(150)))
model.add(Dense(vocab_size, activation='softmax'))
adam = Adam(lr=0.01)
model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
history = model.fit(X, y, epochs=5, verbose=1)
#print model.summary()
print(model)

Epoch 1/5
208/208 [==============================] - 9s 17ms/step - loss: 7.0059 - accuracy: 0.0444
Epoch 2/5
208/208 [==============================] - 4s 18ms/step - loss: 6.4318 - accuracy: 0.0462
Epoch 3/5
208/208 [==============================] - 4s 19ms/step - loss: 6.2008 - accuracy: 0.0522
Epoch 4/5
208/208 [==============================] - 4s 20ms/step - loss: 5.9564 - accuracy: 0.0644
Epoch 5/5
208/208 [==============================] - 3s 17ms/step - loss: 5.6438 - accuracy: 0.0800


# GRU (Gated Recurrent Unit)

In [42]:
import collections
#import helper
import numpy as np
#import projectTest as tests

from keras.preprocessing.text import Tokenizer
#from keras.preprocessing.sequence import pad_sequences
from keras.models import Model, Sequential
from keras.layers import GRU, Input, Dense, TimeDistributed, Activation, RepeatVector, Bidirectional, Dropout, LSTM
#from keras.layers.embeddings import Embedding
from keras.optimizers import Adam
from keras.losses import sparse_categorical_crossentropy

In [43]:
model = Sequential()
model.add(Embedding(vocab_size, 256, input_length=3))
model.add(GRU(256))    
model.add(Dense(vocab_size, activation='softmax'))
adam = Adam(lr=0.01)
model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
history = model.fit(X, y, epochs=5, verbose=1)
#print model.summary()
print(model)

Epoch 1/5


C:\Users\rakesh\anaconda3\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


208/208 [==============================] - 6s 16ms/step - loss: 7.0158 - accuracy: 0.0512
Epoch 2/5
208/208 [==============================] - 4s 17ms/step - loss: 5.8890 - accuracy: 0.0996
Epoch 3/5
208/208 [==============================] - 3s 16ms/step - loss: 4.2688 - accuracy: 0.2191
Epoch 4/5
208/208 [==============================] - 3s 16ms/step - loss: 2.7215 - accuracy: 0.4168
Epoch 5/5
208/208 [==============================] - 3s 15ms/step - loss: 1.7835 - accuracy: 0.5933


# Bidirectional GRU

In [44]:
model = Sequential()
model.add(Embedding(vocab_size, 256, input_length=3))
model.add(Bidirectional(GRU(128)))    
model.add(Dense(vocab_size, activation='softmax'))
adam = Adam(lr=0.01)
model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
history = model.fit(X, y, epochs=5, verbose=1)
#print model.summary()
print(model)

Epoch 1/5
208/208 [==============================] - 7s 16ms/step - loss: 6.9758 - accuracy: 0.0570
Epoch 2/5
208/208 [==============================] - 3s 15ms/step - loss: 5.6371 - accuracy: 0.1106
Epoch 3/5
208/208 [==============================] - 3s 15ms/step - loss: 3.8532 - accuracy: 0.2599
Epoch 4/5
208/208 [==============================] - 3s 15ms/step - loss: 2.4137 - accuracy: 0.4753
Epoch 5/5
208/208 [==============================] - 3s 15ms/step - loss: 1.6803 - accuracy: 0.6180


# RNN

In [46]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [47]:
model = Sequential()
model.add(Embedding(vocab_size, 256, input_length=3))
model.add(layers.SimpleRNN(1000))    
model.add(Dense(vocab_size, activation='softmax'))
adam = Adam(lr=0.01)
model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
history = model.fit(X, y, epochs=5, verbose=1)
#print model.summary()
print(model)

Epoch 1/5
208/208 [==============================] - 9s 40ms/step - loss: 23.7185 - accuracy: 0.0027
Epoch 2/5
208/208 [==============================] - 8s 41ms/step - loss: 27.6835 - accuracy: 0.0050
Epoch 3/5
208/208 [==============================] - 8s 39ms/step - loss: 28.7991 - accuracy: 0.0074
Epoch 4/5
208/208 [==============================] - 8s 40ms/step - loss: 26.8211 - accuracy: 0.0050
Epoch 5/5
208/208 [==============================] - 8s 39ms/step - loss: 27.9180 - accuracy: 0.0056
